site_name: 携笔强军
site_url: https://xbqj.github.io
site_description: 携笔强军——大学生参军入伍帮助与支持
theme:
  name: material
  language: zh
  favicon: images/favicon.png
  logo: images/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: light-blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: teal
      accent: light-blue
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.path

  font:
    text: Sans Serif
    code: Sans Mono

nav:
  - 首页: index.md
  - 前言: why.md
  - 如何参军: how.md
  - 关于我们: about.md
  - 联系我们: contact.md
